// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgYmevc95n8X-wz8F-udiZZQ10oC_Ndc0',
    appId: '1:500903005311:web:47053117810c0f0c1d434a',
    messagingSenderId: '500903005311',
    projectId: 'alimudofarm',
    authDomain: 'alimudofarm.firebaseapp.com',
    storageBucket: 'alimudofarm.firebasestorage.app',
    measurementId: 'G-X600MP09CW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfDJOXoRVnNmbw1aL07AtnYX_pndSZWVE',
    appId: '1:500903005311:android:6cc3d4d66f6b27f41d434a',
    messagingSenderId: '500903005311',
    projectId: 'alimudofarm',
    storageBucket: 'alimudofarm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDEcpl1T_E0phKq1vdsR-llPUwUv3lFGw',
    appId: '1:500903005311:ios:06ad939d297dede11d434a',
    messagingSenderId: '500903005311',
    projectId: 'alimudofarm',
    storageBucket: 'alimudofarm.firebasestorage.app',
    iosBundleId: 'com.example.alim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDEcpl1T_E0phKq1vdsR-llPUwUv3lFGw',
    appId: '1:500903005311:ios:06ad939d297dede11d434a',
    messagingSenderId: '500903005311',
    projectId: 'alimudofarm',
    storageBucket: 'alimudofarm.firebasestorage.app',
    iosBundleId: 'com.example.alim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgYmevc95n8X-wz8F-udiZZQ10oC_Ndc0',
    appId: '1:500903005311:web:acfdced18c7c4c091d434a',
    messagingSenderId: '500903005311',
    projectId: 'alimudofarm',
    authDomain: 'alimudofarm.firebaseapp.com',
    storageBucket: 'alimudofarm.firebasestorage.app',
    measurementId: 'G-WDJY595167',
  );
}
